import type { CSSProperties } from "react";

export const LINE_HEIGHT_PX = 21;

export const s = {
  shell: {
    display: "flex",
    flexDirection: "column",
    borderRadius: 8,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-surface)",
    overflow: "hidden",
  } satisfies CSSProperties,
  shellFill: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
    minHeight: 0,
    borderRadius: 8,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-surface)",
    overflow: "hidden",
  } satisfies CSSProperties,
  metaBar: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "8px 12px",
    borderBottom: "1px solid var(--border)",
    fontSize: 12,
    color: "var(--text-muted)",
    flexShrink: 0,
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  fileName: {
    fontFamily: "var(--font-mono, ui-monospace, SFMono-Regular, Menlo, monospace)",
    fontSize: 12.5,
    fontWeight: 600,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  tokens: { marginLeft: "auto", fontSize: 11.5 } satisfies CSSProperties,
  pane: {
    background: "var(--bg)",
  } satisfies CSSProperties,
  paneFill: {
    flex: 1,
    minHeight: 0,
    overflow: "auto",
    background: "var(--bg)",
  } satisfies CSSProperties,
  editorRows: {
    display: "flex",
    alignItems: "flex-start",
    minHeight: "100%",
  } satisfies CSSProperties,
  gutterCol: { flexShrink: 0, paddingTop: 10 } satisfies CSSProperties,
  gutterLine: {
    width: 40,
    textAlign: "right",
    paddingRight: 12,
    color: "var(--text-muted)",
    userSelect: "none",
    fontFamily: "var(--font-mono, ui-monospace, SFMono-Regular, Menlo, monospace)",
    fontVariantNumeric: "tabular-nums",
    fontSize: 12.5,
    lineHeight: "21px",
    minHeight: 21,
  } satisfies CSSProperties,
  textarea: {
    flex: 1,
    minWidth: 0,
    resize: "none",
    overflow: "hidden",
    border: "none",
    borderRadius: 0,
    outline: "none",
    background: "transparent",
    color: "var(--text-primary)",
    fontFamily: "var(--font-mono, ui-monospace, SFMono-Regular, Menlo, monospace)",
    fontSize: 12.5,
    lineHeight: "21px",
    padding: "10px 12px 10px 0",
    whiteSpace: "pre",
    boxSizing: "border-box",
  } satisfies CSSProperties,
} as const;
