import type { CSSProperties } from "react";

/** Co-located styles for Agent → Stats tab (design StatsTab). */
export const s = {
  wrap: { display: "flex", flexDirection: "column", gap: 16 } satisfies CSSProperties,
  kpiRow: { display: "flex", gap: 12, marginBottom: 4 } satisfies CSSProperties,
  kpi: {
    flex: 1,
    padding: 15,
    borderRadius: 9,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    minWidth: 0,
  } satisfies CSSProperties,
  kpiHead: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  } satisfies CSSProperties,
  kpiLabel: {
    fontSize: 11,
    fontWeight: 600,
    color: "var(--text-muted)",
    letterSpacing: "0.03em",
  } satisfies CSSProperties,
  kpiValueRow: {
    display: "flex",
    alignItems: "baseline",
    gap: 6,
    marginTop: 10,
  } satisfies CSSProperties,
  kpiValue: {
    fontSize: 26,
    fontWeight: 700,
    letterSpacing: "-0.02em",
  } satisfies CSSProperties,
  kpiSuffix: { fontSize: 15, color: "var(--text-muted)" } satisfies CSSProperties,
  grid2: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 16,
  } satisfies CSSProperties,
  cardBody: { padding: "4px 0 0" } satisfies CSSProperties,
  emptyHint: {
    fontSize: 12.5,
    color: "var(--text-muted)",
    padding: "12px 0 4px",
    lineHeight: 1.45,
  } satisfies CSSProperties,
  sevBars: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    paddingTop: 8,
  } satisfies CSSProperties,
  sevRow: {
    display: "grid",
    gridTemplateColumns: "90px 1fr 36px",
    gap: 10,
    alignItems: "center",
    fontSize: 12,
  } satisfies CSSProperties,
  sevTrack: {
    height: 8,
    borderRadius: 4,
    background: "var(--bg-hover)",
    overflow: "hidden",
  } satisfies CSSProperties,
  sevFill: (color: string, pct: number): CSSProperties => ({
    width: `${pct}%`,
    height: "100%",
    background: color,
    borderRadius: 4,
  }),
  legend: {
    display: "flex",
    gap: 14,
    marginTop: 12,
    fontSize: 11,
    color: "var(--text-secondary)",
    flexWrap: "wrap",
  } satisfies CSSProperties,
  legendItem: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
  } satisfies CSSProperties,
  swatch: (color: string): CSSProperties => ({
    width: 9,
    height: 9,
    borderRadius: 2,
    background: color,
  }),
  table: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    overflow: "hidden",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  tableHead: {
    display: "grid",
    gridTemplateColumns: "150px 60px 70px 80px 70px 70px 90px",
    gap: 10,
    padding: "9px 14px",
    background: "var(--bg-surface)",
    borderBottom: "1px solid var(--border)",
    fontSize: 10.5,
    fontWeight: 700,
    letterSpacing: "0.04em",
    color: "var(--text-muted)",
    textTransform: "uppercase",
  } satisfies CSSProperties,
  tableRow: (last: boolean): CSSProperties => ({
    display: "grid",
    gridTemplateColumns: "150px 60px 70px 80px 70px 70px 90px",
    gap: 10,
    padding: "10px 14px",
    borderBottom: last ? "none" : "1px solid var(--border)",
    alignItems: "center",
    fontSize: 12,
  }),
  muted: { color: "var(--text-secondary)", fontSize: 11 } satisfies CSSProperties,
  prLink: { color: "var(--accent-text)" } satisfies CSSProperties,
  donutWrap: { display: "grid", placeItems: "center", paddingTop: 6 } satisfies CSSProperties,
} as const;
