import type { CSSProperties } from "react";

const MONO = "ui-monospace, SFMono-Regular, Menlo, monospace";

export const s = {
  card: {
    borderRadius: 8,
    borderStyle: "solid",
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderTopColor: "var(--border)",
    borderRightColor: "var(--border)",
    borderBottomColor: "var(--border)",
    borderLeftColor: "var(--border)",
    background: "var(--bg-elevated)",
    paddingTop: 18,
    paddingRight: 20,
    paddingBottom: 18,
    paddingLeft: 20,
    display: "flex",
    flexDirection: "column",
    gap: 16,
  } satisfies CSSProperties,
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  headerLabel: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    minWidth: 0,
  } satisfies CSSProperties,
  headerTitle: {
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  actions: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  } satisfies CSSProperties,
  toggle: {
    display: "inline-flex",
    borderRadius: 6,
    overflow: "hidden",
    borderStyle: "solid",
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderTopColor: "var(--border)",
    borderRightColor: "var(--border)",
    borderBottomColor: "var(--border)",
    borderLeftColor: "var(--border)",
  } satisfies CSSProperties,
  toggleButton: (active: boolean): CSSProperties => ({
    fontFamily: "inherit",
    fontSize: 12,
    fontWeight: 500,
    lineHeight: 1.2,
    cursor: "pointer",
    borderStyle: "none",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    paddingTop: 5,
    paddingRight: 10,
    paddingBottom: 5,
    paddingLeft: 10,
    background: active ? "var(--accent-bg)" : "transparent",
    color: active ? "var(--accent-text)" : "var(--text-muted)",
  }),
  stats: {
    display: "flex",
    flexWrap: "wrap",
    gap: 20,
  } satisfies CSSProperties,
  stat: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
  } satisfies CSSProperties,
  statValue: {
    fontSize: 20,
    fontWeight: 600,
    lineHeight: 1.1,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  statLabel: {
    fontSize: 11,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  banner: {
    fontSize: 13,
    color: "var(--warn)",
    borderRadius: 6,
    paddingTop: 8,
    paddingRight: 10,
    paddingBottom: 8,
    paddingLeft: 10,
    borderStyle: "solid",
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderTopColor: "var(--warn)",
    borderRightColor: "var(--warn)",
    borderBottomColor: "var(--warn)",
    borderLeftColor: "var(--warn)",
  } satisfies CSSProperties,
  note: {
    margin: 0,
    fontSize: 12,
    lineHeight: 1.45,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  empty: {
    fontSize: 13,
    color: "var(--text-muted)",
    margin: 0,
  } satisfies CSSProperties,
  skeleton: {
    height: 96,
    borderRadius: 6,
    background: "var(--bg-primary)",
  } satisfies CSSProperties,
  summaryBox: {
    borderRadius: 8,
    background: "var(--bg-primary)",
    paddingTop: 12,
    paddingRight: 14,
    paddingBottom: 12,
    paddingLeft: 14,
    display: "flex",
    flexDirection: "column",
    gap: 6,
  } satisfies CSSProperties,
  summaryText: {
    margin: 0,
    fontSize: 13,
    lineHeight: 1.55,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  tree: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
  } satisfies CSSProperties,
  symbol: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } satisfies CSSProperties,
  symbolHeader: {
    display: "flex",
    alignItems: "baseline",
    flexWrap: "wrap",
    gap: 8,
  } satisfies CSSProperties,
  symbolName: {
    fontFamily: MONO,
    fontSize: 13,
    fontWeight: 600,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  symbolKind: {
    fontSize: 11,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  symbolFile: {
    fontFamily: MONO,
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  sectionLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  list: {
    margin: 0,
    padding: 0,
    listStyleType: "none",
    display: "flex",
    flexDirection: "column",
    gap: 4,
  } satisfies CSSProperties,
  listItem: {
    fontFamily: MONO,
    fontSize: 12,
    lineHeight: 1.45,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  link: {
    color: "var(--accent-text)",
    textDecorationLine: "none",
  } satisfies CSSProperties,
  tag: {
    display: "inline-block",
    fontFamily: MONO,
    fontSize: 12,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  details: {
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  summaryToggle: {
    cursor: "pointer",
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  priorRow: {
    fontSize: 12,
    lineHeight: 1.5,
    color: "var(--text-secondary)",
    marginTop: 6,
  } satisfies CSSProperties,
} as const;
