import type { CSSProperties } from "react";

/** Colocated JS style objects — not Tailwind (client/INSIGHTS.md). */
export const s = {
  header: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    marginBottom: 14,
  } satisfies CSSProperties,
  topRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
  } satisfies CSSProperties,
  eyebrow: {
    display: "inline-flex",
    alignItems: "center",
    gap: 10,
    minWidth: 0,
  } satisfies CSSProperties,
  eyebrowText: {
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: "0.07em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  right: {
    marginLeft: "auto",
    display: "inline-flex",
    alignItems: "center",
    gap: 10,
    flexShrink: 0,
  } satisfies CSSProperties,
  stats: {
    display: "flex",
    alignItems: "baseline",
    gap: 8,
    fontSize: 16,
    fontWeight: 600,
    color: "var(--text-primary)",
    paddingLeft: 24,
  } satisfies CSSProperties,
  statsSep: {
    color: "var(--text-muted)",
    fontWeight: 500,
  } satisfies CSSProperties,
  add: { color: "var(--code-add-text)", fontVariantNumeric: "tabular-nums" } satisfies CSSProperties,
  del: { color: "var(--code-del-text)", fontVariantNumeric: "tabular-nums" } satisfies CSSProperties,
  toggle: {
    display: "inline-flex",
    borderRadius: 7,
    overflow: "hidden",
    borderStyle: "solid",
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderTopColor: "var(--border)",
    borderRightColor: "var(--border)",
    borderBottomColor: "var(--border)",
    borderLeftColor: "var(--border)",
  } satisfies CSSProperties,
  toggleButton: (active: boolean): CSSProperties => ({
    fontSize: 12,
    fontWeight: 500,
    padding: "5px 12px",
    cursor: "pointer",
    border: "none",
    background: active ? "var(--accent-bg)" : "transparent",
    color: active ? "var(--accent-text)" : "var(--text-muted)",
  }),
  banner: {
    fontSize: 13,
    color: "var(--warn)",
    background: "var(--warn-bg, transparent)",
    borderRadius: 6,
    padding: "8px 10px",
    borderStyle: "solid",
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderTopColor: "var(--warn)",
    borderRightColor: "var(--warn)",
    borderBottomColor: "var(--warn)",
    borderLeftColor: "var(--warn)",
    display: "flex",
    flexDirection: "column",
    gap: 2,
  } satisfies CSSProperties,
  splitLine: {
    fontSize: 12,
    color: "var(--warn)",
  } satisfies CSSProperties,
  empty: {
    fontSize: 13,
    color: "var(--text-muted)",
    paddingLeft: 24,
  } satisfies CSSProperties,
  tokenHint: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    paddingLeft: 24,
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  tokenHintIcon: { color: "var(--warn)", flexShrink: 0 } satisfies CSSProperties,
} as const;
