import type { CSSProperties } from "react";

/** Colocated JS style objects — not Tailwind (client/INSIGHTS.md). */
export const s = {
  row: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 10,
    marginBottom: 10,
  } satisfies CSSProperties,
  toggle: {
    display: "inline-flex",
    borderRadius: 7,
    overflow: "hidden",
    borderStyle: "solid",
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderTopColor: "var(--border)",
    borderRightColor: "var(--border)",
    borderBottomColor: "var(--border)",
    borderLeftColor: "var(--border)",
  } satisfies CSSProperties,
  toggleButton: (active: boolean): CSSProperties => ({
    fontSize: 12,
    fontWeight: 500,
    padding: "5px 12px",
    cursor: "pointer",
    border: "none",
    background: active ? "var(--accent-bg)" : "transparent",
    color: active ? "var(--accent-text)" : "var(--text-muted)",
  }),
  banner: {
    flexBasis: "100%",
    fontSize: 13,
    color: "var(--warn)",
    background: "var(--warn-bg, transparent)",
    borderRadius: 6,
    padding: "8px 10px",
    borderStyle: "solid",
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderTopColor: "var(--warn)",
    borderRightColor: "var(--warn)",
    borderBottomColor: "var(--warn)",
    borderLeftColor: "var(--warn)",
    display: "flex",
    flexDirection: "column",
    gap: 2,
  } satisfies CSSProperties,
  splitLine: {
    fontSize: 12,
    color: "var(--warn)",
  } satisfies CSSProperties,
  empty: {
    fontSize: 13,
    color: "var(--text-muted)",
    marginBottom: 10,
  } satisfies CSSProperties,
} as const;
