import type { CSSProperties } from "react";

export const s = {
  card: {
    // Fills the grid cell so the pair stays level (OverviewTab/styles.ts).
    height: "100%",
    boxSizing: "border-box",
    borderRadius: 8,
    borderStyle: "solid",
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderTopColor: "var(--border)",
    borderRightColor: "var(--border)",
    borderBottomColor: "var(--border)",
    borderLeftColor: "var(--border)",
    background: "var(--bg-elevated)",
    paddingTop: 18,
    paddingRight: 20,
    paddingBottom: 18,
    paddingLeft: 20,
    display: "flex",
    flexDirection: "column",
    gap: 16,
  } satisfies CSSProperties,
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  } satisfies CSSProperties,
  headerLabel: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    minWidth: 0,
  } satisfies CSSProperties,
  headerTitle: {
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  summary: {
    margin: 0,
    fontSize: 15,
    fontStyle: "italic",
    fontWeight: 400,
    lineHeight: 1.5,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  scopeGrid: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) minmax(0, 1fr)",
    columnGap: 32,
    rowGap: 16,
  } satisfies CSSProperties,
  scopeHeading: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    marginBottom: 10,
  } satisfies CSSProperties,
  inScopeLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "var(--ok)",
  } satisfies CSSProperties,
  outScopeLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  sectionLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.08em",
    color: "var(--text-muted)",
    textTransform: "uppercase",
  } satisfies CSSProperties,
  list: {
    margin: 0,
    padding: 0,
    listStyleType: "none",
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } satisfies CSSProperties,
  listItem: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    fontSize: 13,
    lineHeight: 1.45,
  } satisfies CSSProperties,
  inScopeText: {
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  outScopeText: {
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  bullet: (color: string): CSSProperties => ({
    width: 5,
    height: 5,
    borderRadius: 999,
    background: color,
    marginTop: 6,
    flexShrink: 0,
  }),
  divider: {
    height: 1,
    background: "var(--border)",
  } satisfies CSSProperties,
  tags: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
  } satisfies CSSProperties,
  tag: (color: string, selected: boolean): CSSProperties => ({
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12,
    fontWeight: 500,
    fontFamily: "inherit",
    lineHeight: 1.2,
    color: "var(--text-primary)",
    background: "transparent",
    cursor: "pointer",
    borderRadius: 6,
    paddingTop: 5,
    paddingRight: 10,
    paddingBottom: 5,
    paddingLeft: 8,
    borderStyle: "solid",
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderTopColor: color,
    borderRightColor: color,
    borderBottomColor: color,
    borderLeftColor: color,
    outlineStyle: selected ? "solid" : "none",
    outlineWidth: selected ? 2 : 0,
    outlineColor: selected ? "var(--accent)" : "transparent",
    outlineOffset: 2,
  }),
  detail: {
    marginTop: 12,
    borderRadius: 8,
    background: "var(--bg-primary)",
    paddingTop: 12,
    paddingRight: 14,
    paddingBottom: 12,
    paddingLeft: 14,
    display: "flex",
    flexDirection: "column",
    gap: 10,
  } satisfies CSSProperties,
  detailText: {
    margin: 0,
    fontSize: 13,
    lineHeight: 1.55,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  inlineCode: {
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    fontSize: 12,
    fontStyle: "normal",
    background: "var(--accent-bg)",
    color: "var(--accent-text)",
    borderRadius: 4,
    paddingTop: 1,
    paddingRight: 5,
    paddingBottom: 1,
    paddingLeft: 5,
  } satisfies CSSProperties,
  fileRef: {
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  meta: {
    fontSize: 12,
    color: "var(--text-muted)",
    display: "flex",
    flexDirection: "column",
    gap: 4,
  } satisfies CSSProperties,
  missing: {
    fontSize: 12,
    color: "var(--text-muted)",
    margin: 0,
    lineHeight: 1.45,
  } satisfies CSSProperties,
  banner: {
    fontSize: 13,
    color: "var(--warn)",
    background: "var(--warn-bg, transparent)",
    borderRadius: 6,
    paddingTop: 8,
    paddingRight: 10,
    paddingBottom: 8,
    paddingLeft: 10,
    borderStyle: "solid",
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderTopColor: "var(--warn)",
    borderRightColor: "var(--warn)",
    borderBottomColor: "var(--warn)",
    borderLeftColor: "var(--warn)",
  } satisfies CSSProperties,
  empty: {
    fontSize: 13,
    color: "var(--text-muted)",
    margin: 0,
  } satisfies CSSProperties,
  actions: {
    display: "flex",
    gap: 8,
  } satisfies CSSProperties,
} as const;
